version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: mamis-com-carinho-DB
    environment:
      POSTGRES_DB: mamisdb
      POSTGRES_USER: mamis
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - mamis-postgres-data:/var/lib/postgresql/data
    restart: always
volumes:
  mamis-postgres-data:
